/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "tertiary-fixed": "#89f5e7",
        "on-primary": "#ffffff",
        "on-background": "#131b2e",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d2d9f4",
        "on-primary-fixed-variant": "#0039b5",
        "on-primary-container": "#cad3ff",
        "secondary": "#904d00",
        "secondary-fixed-dim": "#ffb77d",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dce1ff",
        "on-secondary-fixed": "#2f1500",
        "secondary-fixed": "#ffdcc3",
        "surface-tint": "#2151da",
        "on-surface": "#131b2e",
        "secondary-container": "#fe932c",
        "primary-fixed-dim": "#b7c4ff",
        "on-secondary": "#ffffff",
        "background": "#faf8ff",
        "on-tertiary-fixed-variant": "#005049",
        "surface-container-low": "#f2f3ff",
        "inverse-surface": "#283044",
        "on-secondary-fixed-variant": "#6e3900",
        "inverse-on-surface": "#eef0ff",
        "on-tertiary-fixed": "#00201d",
        "primary": "#0037b0",
        "surface": "#faf8ff",
        "error": "#ba1a1a",
        "surface-variant": "#dae2fd",
        "outline": "#747686",
        "surface-container": "#eaedff",
        "on-surface-variant": "#434655",
        "error-container": "#ffdad6",
        "on-secondary-container": "#663500",
        "surface-container-high": "#e2e7ff",
        "primary-container": "#1d4ed8",
        "surface-bright": "#faf8ff",
        "inverse-primary": "#b7c4ff",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#6bd8cb",
        "tertiary-container": "#00685f",
        "on-primary-fixed": "#001551",
        "surface-container-highest": "#dae2fd",
        "outline-variant": "#c4c5d7",
        "on-tertiary-container": "#7be7d9",
        "tertiary": "#004e47",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        margin: "1.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        "title-md": ["var(--font-plus-jakarta-sans)"],
        "body-md": ["var(--font-plus-jakarta-sans)"],
        "headline-lg": ["var(--font-plus-jakarta-sans)"],
        "label-lg": ["var(--font-inter)"],
        "label-md": ["var(--font-inter)"],
        "headline-sm": ["var(--font-plus-jakarta-sans)"],
        "headline-lg-mobile": ["var(--font-plus-jakarta-sans)"],
        "display": ["var(--font-plus-jakarta-sans)"],
        "label-sm": ["var(--font-inter)"],
        "body-sm": ["var(--font-plus-jakarta-sans)"],
        "body-lg": ["var(--font-plus-jakarta-sans)"],
        "headline-md": ["var(--font-plus-jakarta-sans)"],
        "display-mobile": ["var(--font-plus-jakarta-sans)"],
      },
      fontSize: {
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "display-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
}